%YAML 1.2
---
name: 'tjena_blank'                  # ideally no spaces
gpu: 1                                 # gpu id to process on

dataset: 
  num_chunks: 10000000                   # newest nof chunks to parse
  allow_less_chunks: true
  train_ratio: 0.90                    # trainingset ratio
  # For separated test and train data.
  input_train: '/home/ssonning/Documents/database.lichess.org/standard/supervised-[123456789]/' # supports glob
  input_test: '/home/ssonning/Documents/database.lichess.org/standard/supervised-10/'  # supports glob
  # For a one-shot run with all data in one directory.
  #input: '/work/lc0/data/'
  train_workers: 16
  test_workers: 8

training:
    swa: true
    swa_output: true
    swa_steps: 25
    swa_max_n: 10
    mask_legal_moves: true
    renorm: true
    renorm_max_r: 4.0
    renorm_max_d: 3.0
    q_ratio: 0.0
    max_grad_norm: 3.5
    batch_size: 1024                   # training batch
    num_batch_splits: 1
    test_steps: 250                    # eval test set values after this many steps
    num_test_positions: 10000
    train_avg_report_steps: 50        # training reports its average values after this many steps.
    total_steps: 250000                  # terminate after these steps
    warmup_steps: 125
    checkpoint_steps: 1000          # optional frequency for checkpointing before finish
    shuffle_size: 50000               # size of the shuffle buffer
    lr_values:                         # list of learning rates
        - 0.0003
        - 0.0003
    lr_boundaries:                     # list of boundaries
        - 100000
    policy_loss_weight: 1.5            # weight of policy loss
    value_loss_weight: 0.25            # weight of value loss
    moves_left_loss_weight: 0.1
    reg_loss_weight: 1.0
    path: '/home/ssonning/Documents/networks/'         # network storage dir
    precision: 'half'
    trainstop_path: '/home/ssonning/Documents/networks/trainstop'
    # lookahead_optimizer: true
    # gammareg: true

model:
  filters: 128
  residual_blocks: 10
  se_ratio: 4
...
